### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by Bhavik-Ardeshna** [kritikaparmar-programmer/HealthCheck#5]
when i run command 
```
flask run 
```
After installing all requirement it's giving me this error....I tried many time but It didn't work for me.
![Screenshot from 2021-02-18 13-07-04](https://user-images.githubusercontent.com/58507059/108321768-9e79cb00-71ea-11eb-8aca-7e56e36fe622.png)

**Comment by kritikaparmar-programmer** [comment]
Hey, @Bhavik-Ardeshna I looked into the error, it's because the model was pickeled in sklearn 0.21.1 version and now we are unpickling it in the latest version, which is causing this problem. IIf you want to work on this issue, let me know otherwise I'll work on it :) 
Thanks for raising this issue!

**Comment by kritikaparmar-programmer** [comment]
Hey, @Bhavik-Ardeshna I looked into the error, it's because the model was pickeled in sklearn 0.21.1 version and now we are unpickling it in the latest version, which is causing this problem. IIf you want to work on this issue, let me know otherwise I'll work on it :) 
Thanks for raising this issue!

**Comment by Bhavik-Ardeshna** [comment]
@kritikaparmar-programmer Hello,
I participated in GSSoc'21 and I am interested in HealthCheck project and I am really interested in working with HealthCheck.

So, please let me know the solution to debug this and run in my local machine 
:)

**Comment by kritikaparmar-programmer** [comment]
Yes! I'm working on it.

**Comment by MiHarsh** [comment]
Hello Mam, Have you fixed this issue? Or may I try. I am new to Open Source, and solving issues might help me a lot. 
Thanks

**Comment by kritikaparmar-programmer** [comment]
Hey @MiHarsh @Bhavik-Ardeshna @Bindiya21 I think that the problem is resolved now take a look once again by pulling the changes
The problem was with the version of scikit-learn. Do tell me if you're still facing the problem. 
Also try to install scikit-learn first using command - `pip install scikit-learn == 0.21.1`

**Comment by kritikaparmar-programmer** [comment]
Join Slack Community for further discussion 
You can sign up here: https://join.slack.com/t/newworkspace-bzg8318/shared_invite/zt-mkgixmly-GFjx2bFPetz837_V24h_1Q

**Comment by Bhavik-Ardeshna** [comment]
[https://github.com/scikit-learn/scikit-learn/issues/17430](url)

Giving installtion error of scikit-learn specific version error 


```
Collecting scikit-learn==0.21.1
  Using cached scikit-learn-0.21.1.tar.gz (12.2 MB)
Requirement already satisfied: joblib>=0.11 in /home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages (from scikit-learn==0.21.1) (1.0.1)
Requirement already satisfied: numpy>=1.11.0 in /home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages (from scikit-learn==0.21.1) (1.20.1)
Requirement already satisfied: scipy>=0.17.0 in /home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages (from scikit-learn==0.21.1) (1.6.1)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/Desktop/HealthCheck/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ebccgwbz/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ebccgwbz/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zydohb2x
       cwd: /tmp/pip-install-ebccgwbz/scikit-learn/
  Complete output (7 lines):
  Partial import of sklearn during the build process.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
Installing collected packages: scikit-learn
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/Desktop/HealthCheck/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ebccgwbz/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ebccgwbz/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yhu72w5m/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/Desktop/HealthCheck/env/include/site/python3.8/scikit-learn
         cwd: /tmp/pip-install-ebccgwbz/scikit-learn/
    Complete output (87 lines):
    Partial import of sklearn during the build process.
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    blis_info:
      libraries blis not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    openblas_info:
      libraries openblas not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
      libraries satlas not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/system_info.py:1989: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    blas_info:
      libraries blas not found in ['/home/user/Desktop/HealthCheck/env/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/system_info.py:1989: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    blas_src_info:
      NOT AVAILABLE
    
    /home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/system_info.py:1989: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
      NOT AVAILABLE
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ebccgwbz/scikit-learn/setup.py", line 290, in <module>
        setup_package()
      File "/tmp/pip-install-ebccgwbz/scikit-learn/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-install-ebccgwbz/scikit-learn/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1019, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 985, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 66, in configuration
        config.add_subpackage('utils')
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1019, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 985, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/home/user/Desktop/HealthCheck/env/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/utils/setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/Desktop/HealthCheck/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ebccgwbz/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ebccgwbz/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yhu72w5m/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/Desktop/HealthCheck/env/include/site/python3.8/scikit-learn Check the logs for full command output.

```

**Comment by kritikaparmar-programmer** [comment]
Hey @Bhavik-Ardeshna can you please tell your python version?

**Comment by kritikaparmar-programmer** [comment]
Hey, @Bhavik-Ardeshna I saw your error it is coming because the Scikit-learn 0.21 version is supported by Python 3.5-3.7 versions and your version of python is 3.8. Kindly take a look if you can install the python 3.7 version then it'll work.

**Comment by Bhavik-Ardeshna** [comment]
Ohhhk got it, sure I'll look into it..
:)

**Comment by flyingsonu122** [comment]
> Hey, @Bhavik-Ardeshna I saw your error it is coming because the Scikit-learn 0.21 version is supported by Python 3.5-3.7 versions and your version of python is 3.8. Kindly take a look if you can install the python 3.7 version then it'll work.

Whole world is using python 3.9.2 and you are on 3.5-3.7

Atleast make it compatible with 3.8.x

**Comment by mohdaadilf** [comment]
> Hey, @Bhavik-Ardeshna I saw your error it is coming because the Scikit-learn 0.21 version is supported by Python 3.5-3.7 versions and your version of python is 3.8. Kindly take a look if you can install the python 3.7 version then it'll work.

Is there a workaround for this? Not too keen on downgrading Python.

**Comment by kritikaparmar-programmer** [comment]
Hey @flyingsonu122 and @mohdaadilf take a look now, we have resolved the problem, if you're still facing it, contact any one of the mentors.

**Comment by mohdaadilf** [comment]
@kritikaparmar-programmer Unfortunately, still getting issue 'ModuleNotFoundError: No module named 'sklearn.ensemble.forest''. Not able to install the specified scikit-learn module either. Only able to install the latest version. 
Could one of the mentors help?

`Traceback (most recent call last):
  File "d:\project\healthcheck\env\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\Project\HealthCheck\app.py", line 12, in <module>
    classifier = pickle.load(open(filename, 'rb'))
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'`

**Comment by kritikaparmar-programmer** [comment]
Hey, @mohdaadilf  have you taken the pull and updated your forked repo?

**Comment by mohdaadilf** [comment]
@kritikaparmar-programmer Deleted the old folder cloned the project fresh. Hence didn't have to update.
