### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Bindiya21** [kritikaparmar-programmer/HealthCheck#6]
Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/bindiya/HealthCheck/env/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/bindiya/HealthCheck/app.py", line 12, in <module>
    classifier = pickle.load(open(filename, 'rb'))
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

This error is raised

**Comment by kritikaparmar-programmer** [comment]
Refer issue #5 
Closing this issue.
